In [2]:
import numpy as np

In [13]:
c=np.array([1,3,4,5,6,7])

In [4]:
a = np.array(
[
    [2,3,4],[4,5,6]
]
)

In [53]:
b= np.array(
[
    [1,2,3],[6,7,8]
]
)


In [44]:
print(a[1][-3])

4


In [52]:
print(a
    )

[[2 3 4]
 [4 5 6]]


In [20]:
print(a[0][2])

4


In [37]:
fruits=('4','apple',)

In [38]:
print (fruits[1])

apple


In [47]:
print(np.add(a,b))

[[ 3  5  7]
 [10 12 14]]


In [48]:
print(np.subtract(a,b))

[[ 1  1  1]
 [-2 -2 -2]]


In [60]:
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [69]:
b = np.array([[2,3,4],[4,5,6]])

In [71]:
a = np.array([[2,3,4],[4,5,6]])

In [74]:
print(

SyntaxError: incomplete input (149104261.py, line 1)

In [73]:
np.matmul(a,b.T)

array([[29, 47],
       [47, 77]])

In [65]:
type (a)

numpy.ndarray

In [80]:
b=b.T

In [81]:
print(np.matmul(a,b))

[[29 47]
 [47 77]]


In [32]:
num= [4,3,7,6,3,7]
num.sort()


In [33]:
print(num)

[3, 3, 4, 6, 7, 7]


In [27]:
l = len(num)

In [30]:
a = num[int(l/2)]
b = num[int(l/2-.5)]
med = (a + b)/2

In [31]:
print(med)

4.0


In [37]:
a=10
b=11
a=a+b #7
b=a-b #3
a = a-b # 4

In [38]:
print(a,b)

11 10


In [44]:
a=25
b=20
temp=a
a=b
b=temp
print ("a=",a,"b=",b)

a= 20 b= 25


In [46]:
age=int(input("enter age: "))
if age<10:
    print("rate=7")
elif 10<= age <60:
    print("rate=10")
else:
    print("rate=5")



enter age: 60
rate=5


In [48]:
a=int(input("enter a number:"))
b=int(input("enter b number:"))
if a>b:
    print("a is greater")
else:
    print("b is greater")
    

enter a number:12
enter b number:25
b is greater


In [58]:
a=int(input('enter a year:'))
if (a%4==0 and a%100!=0 or a%400==0):
    print('leap year')
else:
    print('not leap year')
        

enter a year:2000
leap year


In [60]:
num= int(input("enter a no:"))
fact=num
while num>1:
    num = num-1
    fact=fact*num
print(fact)


enter a no:5
120
